### ISSUE TITLE
Does kiss assume name of unzipped sources?

### ISSUE THREAD

**Issue by fleckow** [kisslinux/kiss#161]
I was trying to package a Bitbucket source which comes as a [zip file](https://bitbucket.org/rafaelgg/slmenu/get/7e74fa5db73e.zip) named '7e74fa5db73e.zip' but unzips to a directory named 'rafaelgg-slmenu-7e74fa5db73e/' . 

When I run `kiss b`, the source will download and unzip fine, but the build will fail because `make`  cannot find the Makefile .

When I add an explicit `cd rafaelgg-slmenu-7e74fa5db73e/` to the build file, the package will build successfully.

**Comment by dylanaraps** [comment]
This is intentional. We cannot discern the output directory prior to extraction, nor can we specify the output directory (in a portable way). The `unzip` command has no standard so we limit its usage to `unzip <zip_file>`. Thus, a `cd` may be needed in the build file.

I recommend against using `.zip` files for sources as we have far more control over tarballs. You should be able to get the BitBucket source as a tarball. It's worth a look.
