### ISSUE TITLE
Kiss build may kill its parent on build failure

### ISSUE THREAD

**Issue by TAAPArthur** [kisslinux/kiss#203]
When the build fails kiss, will run `kill 0` which will kill all process in its process group. Unless the parent is catching the SIGTERM, it will probably also kill the parent which isn't ideal for scripts.

Its trivial for a script to catch a SIGTERM or run kiss in its own process group, but it seemed like a bad design to have the child process kill its parent.

Thoughts on replacing `kill 0` with `exit 1` or similar?

**Comment by dylanaraps** [comment]
We cannot use `exit` as this won't halt the script on build failure. The code below will still execute due to the usage of a pipe for log files. We also cannot see the return value of the build script as pipe causes all variables to be local (we can't define any either). `kill 0` is the only way to properly halt the script here.

I can reproduce the issue you describe with the following script:

```sh
#!/bin/sh

# build file modified to always fail
kiss b zlib

# will never run due to kill 0 in kiss
echo hi
```

There's nothing I can do to fix this however. I recommend waiting for the C rewrite of the oackage manager. It won't be affected by this issue (among others).

**Comment by TAAPArthur** [comment]
Ok. 
For anyone stumbling on this issue before the package manager rewrite, catching SIGTERM, is a workaround. 
For example,
```
#!/bin/sh
trap "" TERM
...
```
