### ISSUE TITLE
The differences of Linuxes such the Kiss Linux, ...

### ISSUE THREAD

**Issue by abdulbadii** [kisslinux/kiss#213]
Apologize, but really need info honestly what actually are differences of Linux such these :
Linux from scratch, Kiss Linux, Void Linux ?

Thanks

**Comment by konimex** [comment]
A lot of differences between KISS, Void, and LFS are their package managers, and I don't even think Linux From Scratch is an actual distribution (it's essentially a book, but we'll talk about this one in a later date).

KISS is a source-based distribution, Void is a binary distribution.

KISS has its own packaging system (named kiss, of course), and Void has xbps.

KISS and Void has similarities in that they both use musl and LibreSSL, but KISS works on a "it's easier to add new software than to remove existing software" so it's base is super minimal. I'm not familiar with Void to comment about their approach.

Also, since this is *my* observation, I can't speak for Dylan, but his aims for KISS is detailed in https://k1ss.org/guidestones (down, so here's a mirror: https://kiss.armaanb.net/guidestones).

Hope it helps!
