### ISSUE TITLE
Prohibition of special signs breaks kiss a

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/kiss#241]
```
~ $ kiss a | grep ^toybox | kiss a -
Using ssu (to become root)
grep: Unmatched [, [^, [:, [., or [=
ERROR File '/usr/bin/[' exists on filesystem but isn't owned 
```
Let me know if more context is needed.

**Comment by dylanaraps** [comment]
This is not caused by prohibition of special characters. For `kiss a` this restriction only applies to the first argument. This is caused by the swap to `pkg_owner` in `pkg_swap`. The `[` in the filename is being interpreted as regex. This is merely a matter of using grep in fixed string mode. On it.

**Comment by dylanaraps** [comment]
We could also escape the input. Will see which way is better.

**Comment by dylanaraps** [comment]
Pushed 5.5.10 to the repositories. Thanks for the issue. :)
