### ISSUE TITLE
[Feature request] => KISS uses git clone without --depth parameter resulting in huge clones

### ISSUE THREAD

**Issue by x4an** [kisslinux/kiss#270]
The git command in KISS clones repositories without the `--depth` parameter. The place which it effects the most is `vim`. The clone done by KISS is ~50Mb while done with `--depth` parameter is ~16Mb which is a huge difference.

Please put this feature in KISS.

**Comment by dylanaraps** [comment]
As of the latest release git sources are cached. This of course comes with a bigger initial download size as the point of the change was to reduce subsequent fetch times and prevent re-cloning on each build. Vim is a special case as each and every commit becomes a git tag. This becomes an additional 30-40MB of data(!). 

I will make a change to the package manager so that it a) does shallow clones when possible and b) only fetches tags when `@` or `#` is used.

**Comment by dylanaraps** [comment]
Please try the latest master.

**Comment by x4an** [comment]
The problem has been fixed and now `vim` has its size decreased from ~50MB to 16MB. Thanks for the commit. Closing this issue...

**Comment by dylanaraps** [comment]
Will wait a few days before making a release to ensure this doesn't cause any breakage. Let me know if there are any other issues.

**Comment by x4an** [comment]
That's all for now since this was the only problem I ever had with `kiss`. may you merge this commit with KISS linux repo if it is doable?

**Comment by dylanaraps** [comment]
Yes. This will happen in a few days. I want to ensure this does not cause a regression first.

**Comment by aabacchus** [comment]
Commit a4f7765 also fixed a problem that, if a specific branch is given in `sources`, kiss wouldn't pull new remote changes into a local branch (it would fetch them, but then `checkout` the local branch without merging).
Something to bear in mind if anyone decided to revert this.
