### ISSUE TITLE
Versioning package dependencies

### ISSUE THREAD

**Issue by ashinkarov** [kisslinux/kiss#81]
Sorry if this is a wrong place to ask, but it seems that I cannot find this in the documentation.

Is it possible to specify a version (or version range) for a given package dependency?  If not, how do you envision to deal with cases when packages X and Y both depend on Z, but X only works with versions (>= 1.5 and < 2.5), and Y with versions (>= 2.0 and < 3.0)?

**Comment by dylanaraps** [comment]
There is no dependency versioning, however this problem is solved in the following ways.

- Patch the software to work with the newest version of the dependency.
    - Extends to opening a bug report upstream.
- Ship two versions of the dependency.
    - Example: Python2/3, GTK+2/3.
- Vendor the dependency during the build.
    - Example: Firefox needs a 20~ year old autoconf and we build it solely for Firefox as part of its build process.
- Maintain your own repository providing the package and the older version of the dependency.

There are other alternative approaches you can take too. I just see dependency versioning as a messy endeavor and would much rather the software be updated or fixed to support newer versions of their dependencies.
