### ISSUE TITLE
Move from busybox wget to curl for portability

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/kiss#82]
`curl` will always be available as the package manager depends on `git` for updates which pulls in `curl`. This will fix an issue when swapping to another coreutils where `wget` is unavailable.

**Comment by cemkeylan** [comment]
Wget could be removed from the busybox config and added as an independent package. I think wget is much more reliable and faster for downloading large files. Wget's sole purpose is downloading unlike curl, which is a basic command line browser. That's why I think it could be better if we would seperate wget from busybox and revert kiss to wget.

**Comment by dylanaraps** [comment]
`curl` is fine and I'd rather not add a dependency on GNU `wget` to the base system. `curl` is already needed for `git` so the change actually *removes* a dependency if `busybox` is swapped for another coreutils.

Also see:

- https://unix.stackexchange.com/questions/47434/what-is-the-difference-between-curl-and-wget
- https://daniel.haxx.se/docs/curl-vs-wget.html

For our use case, there's no issue with `curl`. We're not doing recursive downloads or anything overly fancy. The links above are limited to GNU `wget` as I don't see `busybox wget` as a contender compared to `curl` regardless.

As an example, `busybox wget ` calls `openssl` via the shell and suppresses all error messages. It also has a low redirection limit of `5` which I've seen prevent a download for a source in the past. 

I don't seen any downsides to our swap to `curl`.

**Comment by cemkeylan** [comment]
I see, that makes sense.
